/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Tasin Khan
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Properties;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.awt.*;
import java.sql.*;
import javax.swing.*;
public class SIngleframe extends javax.swing.JFrame {

    /**
     * Creates new form SIngleframe
     */
    public SIngleframe() {
        initComponents();
        String url = "jdbc:mysql://localhost:3306/tuitiondb";
        String user = "root";
        String password = "";

        Connection conn = null;
        Statement stmt = null;
        ResultSet rs = null;

        try {
            // 1. Connect to the database
//            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection(url, user, password);

            // 2. Create a statement
            stmt = conn.createStatement();

            // 3. Execute a SQL query to retrieve data for 4 rows
            String sql = "SELECT * FROM tuitioncount";
            rs = stmt.executeQuery(sql);

            // 4. Extract data from result set
            int rowCounter = 1;
            while (rs.next()) {
                String name = rs.getString("name");
                int c = rs.getInt("count");

                // Assign each row's value to different JTextFields based on row number
                switch (rowCounter) {
                    case 1:
                        s1.setText(name);
                        c1.setText(String.valueOf(c));
                        break;
                    case 2:
                        s2.setText(name);
                        c2.setText(String.valueOf(c));
                        break;
                    case 3:
                        s3.setText(name);
                        c3.setText(String.valueOf(c));
                        break;
                    case 4:
                        s4.setText(name);
                        c4.setText(String.valueOf(c));
                        break;
                }
                rowCounter++;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            // Close resources
            try {
                if (rs != null) rs.close();
                if (stmt != null) stmt.close();
                if (conn != null) conn.close();
            } catch (SQLException se) {
                se.printStackTrace();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        s4 = new javax.swing.JTextField();
        s1 = new javax.swing.JTextField();
        s2 = new javax.swing.JTextField();
        s3 = new javax.swing.JTextField();
        c4 = new javax.swing.JTextField();
        c1 = new javax.swing.JTextField();
        c2 = new javax.swing.JTextField();
        c3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Day Count");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 42, 223, 85));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Student's Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 42, 223, 85));
        jPanel1.add(s4, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 334, 215, 45));
        jPanel1.add(s1, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 145, 215, 45));
        jPanel1.add(s2, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 208, 215, 45));
        jPanel1.add(s3, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 271, 215, 45));

        c4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(c4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 110, 50));

        c1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 110, 50));

        c2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 110, 50));

        c3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 110, 50));

        jButton1.setBackground(new java.awt.Color(153, 255, 51));
        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 160, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 204, 204));
        jButton2.setText("Increase");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, -1, -1));

        jButton3.setBackground(new java.awt.Color(255, 204, 204));
        jButton3.setText("Increase");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 230, -1, -1));

        jButton4.setBackground(new java.awt.Color(153, 255, 51));
        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 230, -1, -1));

        jButton5.setBackground(new java.awt.Color(153, 255, 51));
        jButton5.setText("Clear");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 300, -1, -1));

        jButton6.setBackground(new java.awt.Color(255, 204, 204));
        jButton6.setText("Increase");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 300, -1, -1));

        jButton7.setBackground(new java.awt.Color(255, 204, 204));
        jButton7.setText("Increase");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 370, -1, -1));

        jButton8.setBackground(new java.awt.Color(153, 255, 51));
        jButton8.setText("Clear");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 370, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 856, 487));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String url = "jdbc:mysql://localhost:3306/tuitiondb";
        String user = "root";
        String password = "";
        Connection conn = null;
        PreparedStatement pstmt = null;

        try {
            // Load the MySQL JDBC driver
            Class.forName("com.mysql.cj.jdbc.Driver");

            // Connect to the database
            conn = DriverManager.getConnection(url, user, password);
            String Name = s1.getText();

            // Retrieve the current count value from the text field
            int currentCount = Integer.parseInt(c1.getText());
            int newCount = currentCount + 1; // Increment the count

            // SQL query to update the count value for the user with id "abrar"
            String sql = "UPDATE tuitioncount SET count = ? WHERE name = ?";
            pstmt = conn.prepareStatement(sql);
            pstmt.setInt(1, newCount);
            pstmt.setString(2, Name);  // Setting "abrar" as the user ID
            pstmt.executeUpdate();

            // Update the text field with the new count
            c1.setText(String.valueOf(newCount));

        } catch (Exception ex) {
            ex.printStackTrace();
        } finally {
            try {
                if (pstmt != null) pstmt.close();
                if (conn != null) conn.close();
            } catch (SQLException se) {
                se.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String url = "jdbc:mysql://localhost:3306/tuitiondb";
        String user = "root";
        String password = "";
        Connection conn = null;
        PreparedStatement pstmt = null;

        try {
            // Load the MySQL JDBC driver
            Class.forName("com.mysql.cj.jdbc.Driver");

            // Connect to the database
            conn = DriverManager.getConnection(url, user, password);

            // Get the name from the input field
            String name = s1.getText();

            // SQL query to update the count value to 0 for the specified name
            String updateSql = "UPDATE tuitioncount SET count = 0 WHERE name = ?";
            pstmt = conn.prepareStatement(updateSql);
            pstmt.setString(1, name); // Set the name parameter
            int rowsUpdated = pstmt.executeUpdate(); // Execute the update

            if (rowsUpdated > 0) {
                // Update the count field to show zero
                c1.setText("0");
            } else {
                JOptionPane.showMessageDialog(this, "Name not found in the database.");
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        } finally {
            try {
                if (pstmt != null) pstmt.close();
                if (conn != null) conn.close();
            } catch (SQLException se) {
                se.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String url = "jdbc:mysql://localhost:3306/tuitiondb";
        String user = "root";
        String password = "";
        Connection conn = null;
        PreparedStatement pstmt = null;

        try {
            // Load the MySQL JDBC driver
            Class.forName("com.mysql.cj.jdbc.Driver");

            // Connect to the database
            conn = DriverManager.getConnection(url, user, password);
            String Name = s2.getText();

            // Retrieve the current count value from the text field
            int currentCount = Integer.parseInt(c2.getText());
            int newCount = currentCount + 1; // Increment the count

            // SQL query to update the count value for the user with id "abrar"
            String sql = "UPDATE tuitioncount SET count = ? WHERE name = ?";
            pstmt = conn.prepareStatement(sql);
            pstmt.setInt(1, newCount);
            pstmt.setString(2, Name);  // Setting "abrar" as the user ID
            pstmt.executeUpdate();

            // Update the text field with the new count
            c2.setText(String.valueOf(newCount));

        } catch (Exception ex) {
            ex.printStackTrace();
        } finally {
            try {
                if (pstmt != null) pstmt.close();
                if (conn != null) conn.close();
            } catch (SQLException se) {
                se.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String url = "jdbc:mysql://localhost:3306/tuitiondb";
        String user = "root";
        String password = "";
        Connection conn = null;
        PreparedStatement pstmt = null;

        try {
            // Load the MySQL JDBC driver
            Class.forName("com.mysql.cj.jdbc.Driver");

            // Connect to the database
            conn = DriverManager.getConnection(url, user, password);
            String Name = s3.getText();

            // Retrieve the current count value from the text field
            int currentCount = Integer.parseInt(c3.getText());
            int newCount = currentCount + 1; // Increment the count

            // SQL query to update the count value for the user with id "abrar"
            String sql = "UPDATE tuitioncount SET count = ? WHERE name = ?";
            pstmt = conn.prepareStatement(sql);
            pstmt.setInt(1, newCount);
            pstmt.setString(2, Name);  // Setting "abrar" as the user ID
            pstmt.executeUpdate();

            // Update the text field with the new count
            c3.setText(String.valueOf(newCount));

        } catch (Exception ex) {
            ex.printStackTrace();
        } finally {
            try {
                if (pstmt != null) pstmt.close();
                if (conn != null) conn.close();
            } catch (SQLException se) {
                se.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        String url = "jdbc:mysql://localhost:3306/tuitiondb";
        String user = "root";
        String password = "";
        Connection conn = null;
        PreparedStatement pstmt = null;

        try {
            // Load the MySQL JDBC driver
            Class.forName("com.mysql.cj.jdbc.Driver");

            // Connect to the database
            conn = DriverManager.getConnection(url, user, password);
            String Name = s4.getText();

            // Retrieve the current count value from the text field
            int currentCount = Integer.parseInt(c4.getText());
            int newCount = currentCount + 1; // Increment the count

            // SQL query to update the count value for the user with id "abrar"
            String sql = "UPDATE tuitioncount SET count = ? WHERE name = ?";
            pstmt = conn.prepareStatement(sql);
            pstmt.setInt(1, newCount);
            pstmt.setString(2, Name);  // Setting "abrar" as the user ID
            pstmt.executeUpdate();

            // Update the text field with the new count
            c4.setText(String.valueOf(newCount));

        } catch (Exception ex) {
            ex.printStackTrace();
        } finally {
            try {
                if (pstmt != null) pstmt.close();
                if (conn != null) conn.close();
            } catch (SQLException se) {
                se.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         String url = "jdbc:mysql://localhost:3306/tuitiondb";
        String user = "root";
        String password = "";
        Connection conn = null;
        PreparedStatement pstmt = null;

        try {
            // Load the MySQL JDBC driver
            Class.forName("com.mysql.cj.jdbc.Driver");

            // Connect to the database
            conn = DriverManager.getConnection(url, user, password);

            // Get the name from the input field
            String name = s2.getText();

            // SQL query to update the count value to 0 for the specified name
            String updateSql = "UPDATE tuitioncount SET count = 0 WHERE name = ?";
            pstmt = conn.prepareStatement(updateSql);
            pstmt.setString(1, name); // Set the name parameter
            int rowsUpdated = pstmt.executeUpdate(); // Execute the update

            if (rowsUpdated > 0) {
                // Update the count field to show zero
                c2.setText("0");
            } else {
                JOptionPane.showMessageDialog(this, "Name not found in the database.");
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        } finally {
            try {
                if (pstmt != null) pstmt.close();
                if (conn != null) conn.close();
            } catch (SQLException se) {
                se.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         String url = "jdbc:mysql://localhost:3306/tuitiondb";
        String user = "root";
        String password = "";
        Connection conn = null;
        PreparedStatement pstmt = null;

        try {
            // Load the MySQL JDBC driver
            Class.forName("com.mysql.cj.jdbc.Driver");

            // Connect to the database
            conn = DriverManager.getConnection(url, user, password);

            // Get the name from the input field
            String name = s3.getText();

            // SQL query to update the count value to 0 for the specified name
            String updateSql = "UPDATE tuitioncount SET count = 0 WHERE name = ?";
            pstmt = conn.prepareStatement(updateSql);
            pstmt.setString(1, name); // Set the name parameter
            int rowsUpdated = pstmt.executeUpdate(); // Execute the update

            if (rowsUpdated > 0) {
                // Update the count field to show zero
                c3.setText("0");
            } else {
                JOptionPane.showMessageDialog(this, "Name not found in the database.");
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        } finally {
            try {
                if (pstmt != null) pstmt.close();
                if (conn != null) conn.close();
            } catch (SQLException se) {
                se.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
         String url = "jdbc:mysql://localhost:3306/tuitiondb";
        String user = "root";
        String password = "";
        Connection conn = null;
        PreparedStatement pstmt = null;

        try {
            // Load the MySQL JDBC driver
            Class.forName("com.mysql.cj.jdbc.Driver");

            // Connect to the database
            conn = DriverManager.getConnection(url, user, password);

            // Get the name from the input field
            String name = s4.getText();

            // SQL query to update the count value to 0 for the specified name
            String updateSql = "UPDATE tuitioncount SET count = 0 WHERE name = ?";
            pstmt = conn.prepareStatement(updateSql);
            pstmt.setString(1, name); // Set the name parameter
            int rowsUpdated = pstmt.executeUpdate(); // Execute the update

            if (rowsUpdated > 0) {
                // Update the count field to show zero
                c4.setText("0");
            } else {
                JOptionPane.showMessageDialog(this, "Name not found in the database.");
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        } finally {
            try {
                if (pstmt != null) pstmt.close();
                if (conn != null) conn.close();
            } catch (SQLException se) {
                se.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SIngleframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SIngleframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SIngleframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SIngleframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SIngleframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField c1;
    private javax.swing.JTextField c2;
    private javax.swing.JTextField c3;
    private javax.swing.JTextField c4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField s1;
    private javax.swing.JTextField s2;
    private javax.swing.JTextField s3;
    private javax.swing.JTextField s4;
    // End of variables declaration//GEN-END:variables
}
